### ISSUE TITLE
Internationalisation?

### ISSUE THREAD

**Issue by elpatron68** [jedfonner/MattermostOnFire#2]
Hi Jed,

I would like to translate this into German language and thought, the easiest approach would be a forked translated project (as I don´t see any localisation structures in the source code). For my demands, this would be sufficient.

If there would be any demand for other localized versions, it would probably be a better idea to prepare the project to support multiple languages... Perhaps, the user´s language from the Mattermost client could even be transferred to MattermostOnFire?

Regards,
Markus

**Comment by LucileDT** [comment]
As a French, I can say we have some French people who would be happy to have the poll tool in French too! So I think that it would be better if the project was prepared to support multiple languages and then set up something like https://crowdin.com to allow non tech people to translate it in their own language (Crowdin is used for Open Broadcaster Software, I have an account on it and it's pretty easy to use, easier than make a ton of pull requests).

**Comment by jedfonner** [comment]
Great idea.  I'm a little stumped on how to get the user's locale from the request.  AFAIK Mattermost does not send it in the initial request to create the poll. So I'm not sure I can make the i18n dynamic.

I will work on moving the text into a separate json map using ICU Message syntax.  Best case we can figure out how to dynamically pull the right text.  Worst case I can add instructions to define the locale as an environment variable.

**Comment by DarckCrystale** [comment]
@jedfonner did you contact the Mattermost dev team to ask them?

**Comment by jedfonner** [comment]
I submitted a Feature Suggestion: [Include user's language in body of outgoing slash command request](https://mattermost.uservoice.com/forums/306457-general/suggestions/32967817-include-user-s-language-in-body-of-outgoing-slash).  Please add your vote to this to encourage Mattermost to take it into consideration.

**Comment by jedfonner** [comment]
I've created a branch with basic support for specifying a language as an environment config. 

However now I need help with the actual translations.  Anyone available to help translate in German, French, etc before I merge it into master?

**Comment by elpatron68** [comment]
Thanks! I will translate to german.

**Comment by DarckCrystale** [comment]
I can translate to French if needed and if "how to do" is explained :)

**Comment by elpatron68** [comment]
The easiest way is to edit https://github.com/jedfonner/MattermostOnFire/blob/i18next/functions/translations.json and provide it as Gist (https://gist.github.com/) or at [Pastebin](https://pastebin.com/).

Otherwise, you could clone this repository, checkout the `i18next` branch, make your changes, commit them and create a pull request.

**Comment by DarckCrystale** [comment]
Thanks!

**Comment by DarckCrystale** [comment]
Done for me and pull request submitted :)

**Comment by jedfonner** [comment]
@DarckCrystale and elpatron68 - you guys rock!  Thanks so much.  I just merged your PRs into my initial PR and merged all of it to master.

**Comment by elpatron68** [comment]
Just one last question: Updating a running installation to support i18n is the same way than deploying a fresh one?

**Comment by jedfonner** [comment]
@elpatron68 Pretty much. Update your local working directory to the latest code, then set your `mattermost.language` environment variable as explained in the [new Readme section](https://github.com/jedfonner/MattermostOnFire#internationalization), and then run `firebase deploy` (luckily it's all JavaScript so nothing to build locally!)
